In [2]:
import nibabel as nib
import numpy as np
from nibabel.orientations import aff2axcodes
import nibabel.processing

In [2]:
# 读取 NIfTI 文件
nifti_file = "test/20220111_pre_OP_3D_FLAIR_FS_AX_5mm_20220111014643_402.nii.gz"
img = nib.load(nifti_file)

# 获取数据数组
data = img.get_fdata()

In [3]:
# 查看形状和元数据
print("NIfTI 形状:", data.shape)
print("仿射矩阵:", img.affine)
print("数据类型:", data.dtype)
print("体素尺寸 (mm):", img.header.get_zooms())

NIfTI 形状: (1024, 1024, 25)
仿射矩阵: [[ 2.34364823e-01  2.16116919e-03  8.14247876e-03 -1.23858421e+02]
 [-2.18370580e-03  2.30898038e-01  1.02814257e+00 -1.17857437e+02]
 [ 5.69846779e-05 -4.01630439e-02  5.91124773e+00 -3.99858170e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
数据类型: float64
体素尺寸 (mm): (np.float32(0.234375), np.float32(0.234375), np.float32(6.0))


In [4]:
voxel_size = np.sqrt(np.sum(img.affine[:3, :3] ** 2, axis=0))
print("原始体素尺寸:", voxel_size)

原始体素尺寸: [0.234375   0.23437501 5.99999943]


In [5]:
affine_matrix = np.array(img.affine)

print("数据方向:", aff2axcodes(affine_matrix))

数据方向: ('R', 'A', 'S')


In [8]:
img = nib.load("test/20220111_pre_OP_3D_FLAIR_FS_AX_5mm_20220111014643_402.nii.gz")
resampled_img = nibabel.processing.resample_to_output(img, voxel_sizes=(1, 1, 1))
nib.save(resampled_img, "test/resampled_20220111_pre_OP_3D_FLAIR_FS_AX_5mm_20220111014643_402.nii.gz")

In [9]:
# 读取 NIfTI 文件
nifti_file = "test/resampled_20220111_pre_OP_3D_FLAIR_FS_AX_5mm_20220111014643_402_resampled.nii.gz"
img = nib.load(nifti_file)

# 获取数据数组
data = img.get_fdata()

In [10]:
# 查看形状和元数据
print("NIfTI 形状:", data.shape)
print("仿射矩阵:", img.affine)
print("数据类型:", data.dtype)

NIfTI 形状: (244, 265, 185)
仿射矩阵: [[ 1.00000000e+00  2.16116919e-03  8.14247876e-03 -1.23858421e+02]
 [-2.18370580e-03  1.00000000e+00  1.02814257e+00 -1.17857437e+02]
 [ 5.69846779e-05 -4.01630439e-02  1.00000000e+00 -3.99858170e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
数据类型: float64


In [13]:
affine_matrix = np.array(img.affine)

print("数据方向:", aff2axcodes(affine_matrix))

数据方向: ('R', 'A', 'S')


In [11]:
# 加载原始 NIfTI 图像
img = nib.load("test/20220111_pre_OP_3D_FLAIR_FS_AX_5mm_20220111014643_402.nii.gz")

# 获取原始仿射矩阵
affine = img.affine
print("原始仿射矩阵:", affine)

# 手动设置 X 和 Y 轴体素尺寸为相同（修改仿射矩阵）
new_affine = affine.copy()
new_affine[0, 0] = 1.0  # X 轴体素尺寸
new_affine[1, 1] = 1.0  # Y 轴体素尺寸
new_affine[2, 2] = 1.0  # Z 轴体素尺寸

# 创建新的 Nifti1Image 对象，并使用新的仿射矩阵
img_with_new_affine = nib.Nifti1Image(img.get_fdata(), new_affine)

# 保存修改后的图像
nib.save(img_with_new_affine, "test/modified_20220111_pre_OP_3D_FLAIR_FS_AX_5mm_20220111014643_402_with_new_affine.nii.gz")


原始仿射矩阵: [[ 2.34364823e-01  2.16116919e-03  8.14247876e-03 -1.23858421e+02]
 [-2.18370580e-03  2.30898038e-01  1.02814257e+00 -1.17857437e+02]
 [ 5.69846779e-05 -4.01630439e-02  5.91124773e+00 -3.99858170e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [12]:
# 读取 NIfTI 文件
modified_nifti_file = "test/modified_20220111_pre_OP_3D_FLAIR_FS_AX_5mm_20220111014643_402_with_new_affine.nii.gz"
modified_img = nib.load(modified_nifti_file)

# 获取数据数组
modified_data = modified_img.get_fdata()

# 查看形状和元数据
print("NIfTI 形状:", modified_data.shape)
print("仿射矩阵:", modified_img.affine)
print("数据类型:", modified_data.dtype)

modified_voxel_size = np.sqrt(np.sum(modified_img.affine[:3, :3] ** 2, axis=0))
print("原始体素尺寸:", modified_voxel_size)

NIfTI 形状: (1024, 1024, 25)
仿射矩阵: [[ 1.00000000e+00  2.16116919e-03  8.14247876e-03 -1.23858421e+02]
 [-2.18370580e-03  1.00000000e+00  1.02814257e+00 -1.17857437e+02]
 [ 5.69846779e-05 -4.01630439e-02  1.00000000e+00 -3.99858170e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
数据类型: float64
原始体素尺寸: [1.00000239 1.00080854 1.43427454]


# T1

In [20]:
# 读取 NIfTI 文件
t1_test_nifti_file = "test/20220111_pre_OP_3DT1_AX_Gadovist_1mm_20220111014643_1303.nii.gz"
t1_test_img = nib.load(t1_test_nifti_file)

# 获取数据数组
t1_test_data = t1_test_img.get_fdata()

In [21]:
# 查看形状和元数据
print("NIfTI 形状:", t1_test_data.shape)
print("仿射矩阵:", t1_test_img.affine)
print("数据类型:", t1_test_data.dtype)
print("体素尺寸 (mm):", t1_test_img.header.get_zooms())

NIfTI 形状: (1024, 1024, 155)
仿射矩阵: [[ 2.34364823e-01  2.16116919e-03  1.35707960e-03 -1.23876503e+02]
 [-2.18370580e-03  2.30898038e-01  1.71357065e-01 -1.19829010e+02]
 [ 5.69846779e-05 -4.01630439e-02  9.85207736e-01 -4.11954269e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
数据类型: float64
体素尺寸 (mm): (np.float32(0.234375), np.float32(0.234375), np.float32(1.0))


In [22]:
voxel_size = np.sqrt(np.sum(t1_test_img.affine[:3, :3] ** 2, axis=0))
print("原始体素尺寸:", voxel_size)

原始体素尺寸: [0.234375   0.23437501 0.99999968]


In [23]:
affine_matrix = np.array(t1_test_img.affine)

print("数据方向:", aff2axcodes(affine_matrix))

数据方向: ('R', 'A', 'S')


In [24]:
img = nib.load("test/20220111_pre_OP_3DT1_AX_Gadovist_1mm_20220111014643_1303.nii.gz")
resampled_t1_test = nibabel.processing.resample_to_output(t1_test_img, voxel_sizes=(1, 1, 1))
nib.save(resampled_t1_test, "test/resampled_20220111_pre_OP_3DT1_AX_Gadovist_1mm_20220111014643_1303.nii.gz")

In [26]:
# 读取 NIfTI 文件
resample_t1_test_nifti_file = "test/resampled_20220111_pre_OP_3DT1_AX_Gadovist_1mm_20220111014643_1303.nii.gz"
resample_t1_test_img = nib.load(resample_t1_test_nifti_file)

# 获取数据数组
resample_t1_test_data = resample_t1_test_img.get_fdata()

In [27]:
# 查看形状和元数据
print("NIfTI 形状:", resample_t1_test_data.shape)
print("仿射矩阵:", resample_t1_test_img.affine)
print("数据类型:", resample_t1_test_data.dtype)
print("体素尺寸 (mm):", resample_t1_test_img.header.get_zooms())

NIfTI 形状: (244, 266, 194)
仿射矩阵: [[   1.            0.            0.         -123.87650299]
 [   0.            1.            0.         -122.0629425 ]
 [   0.            0.            1.          -82.28221893]
 [   0.            0.            0.            1.        ]]
数据类型: float64
体素尺寸 (mm): (np.float32(1.0), np.float32(1.0), np.float32(1.0))


In [3]:
# 读取 NIfTI 文件
seg_file = "BraTS2021_00495/BraTS2021_00495_seg.nii.gz"
seg_img = nib.load(seg_file)

flair_file = "BraTS2021_00495/BraTS2021_00495_flair.nii.gz"
flair_img = nib.load(flair_file)

# 获取数据数组
seg_data = seg_img.get_fdata()
flair_data = flair_img.get_fdata()

In [4]:
# 查看形状和元数据
print('-----seg-----')
print("NIfTI 形状:", flair_data.shape)
print("仿射矩阵:", flair_img.affine)
print("数据类型:", flair_data.dtype)
print("体素尺寸 (mm):", flair_img.header.get_zooms())

print('-----flair-----')
print("NIfTI 形状:", seg_data.shape)
print("仿射矩阵:", seg_img.affine)
print("数据类型:", seg_data.dtype)
print("体素尺寸 (mm):", flair_img.header.get_zooms())

-----seg-----
NIfTI 形状: (240, 240, 155)
仿射矩阵: [[ -1.  -0.  -0.   0.]
 [ -0.  -1.  -0. 239.]
 [  0.   0.   1.   0.]
 [  0.   0.   0.   1.]]
数据类型: float64
体素尺寸 (mm): (np.float32(1.0), np.float32(1.0), np.float32(1.0))
-----flair-----
NIfTI 形状: (240, 240, 155)
仿射矩阵: [[ -1.   0.   0.  -0.]
 [  0.  -1.   0. 239.]
 [  0.   0.   1.   0.]
 [  0.   0.   0.   1.]]
数据类型: float64
体素尺寸 (mm): (np.float32(1.0), np.float32(1.0), np.float32(1.0))


In [9]:
print("体素尺寸 (mm):", flair_img.header.get_zooms())

体素尺寸 (mm): (np.float32(1.0), np.float32(1.0), np.float32(1.0))


In [1]:
import os
import nibabel as nib

In [2]:
def check_nii_shapes(folder_path):
    # 获取该目录下所有以 .nii.gz 结尾的文件（不包含子文件夹）
    nii_files = [f for f in os.listdir(folder_path) if f.endswith('.nii.gz')]
    
    shape_dict = {}

    for nii_file in nii_files:
        file_path = os.path.join(folder_path, nii_file)
        img = nib.load(file_path)
        shape = img.shape
        shape_dict[nii_file] = shape

    return shape_dict

In [2]:
# 使用方法：
folder_path = 'C:/Users/ajhz839/workwork/Data/preprocessed' 
shapes = check_nii_shapes(folder_path)

# 输出结果
for file_name, shape in shapes.items():
    print(f"{file_name}: {shape}")


20220114_35320313_BSR_20220111_pre_OP_FLAIR.nii.gz: (240, 240, 155)
20220114_35320313_BSR_20220111_pre_OP_fused_mask.nii.gz: (240, 240, 155)
20220114_35320313_BSR_20220111_pre_OP_T1.nii.gz: (240, 240, 155)
20220114_35320313_BSR_20220111_pre_OP_T1ce.nii.gz: (240, 240, 155)
20220114_35320313_BSR_20220111_pre_OP_T2.nii.gz: (240, 240, 155)
20220114_35320313_BSR_20220115_post_OP_FLAIR.nii.gz: (240, 240, 155)
20220114_35320313_BSR_20220115_post_OP_fused_mask.nii.gz: (240, 240, 155)
20220114_35320313_BSR_20220115_post_OP_T1.nii.gz: (240, 240, 155)
20220114_35320313_BSR_20220115_post_OP_T1ce.nii.gz: (240, 240, 155)
20220114_35320313_BSR_20220115_post_OP_T2.nii.gz: (240, 240, 155)
20220114_35320313_BSR_20220414_post_CCRT_1_FLAIR.nii.gz: (240, 240, 160)
20220114_35320313_BSR_20220414_post_CCRT_1_fused_mask.nii.gz: (240, 240, 160)
20220114_35320313_BSR_20220414_post_CCRT_1_T1.nii.gz: (240, 240, 160)
20220114_35320313_BSR_20220414_post_CCRT_1_T1ce.nii.gz: (240, 240, 160)
20220114_35320313_BSR_2022

In [4]:
# 使用方法：
folder_path = 'C:/Users/ajhz839/workwork/Data/BraTS2021_00495' 
shapes = check_nii_shapes(folder_path)

# 输出结果
for file_name, shape in shapes.items():
    print(f"{file_name}: {shape}")

BraTS2021_00495_flair.nii.gz: (240, 240, 155)
BraTS2021_00495_seg.nii.gz: (240, 240, 155)
BraTS2021_00495_t1.nii.gz: (240, 240, 155)
BraTS2021_00495_t1ce.nii.gz: (240, 240, 155)
BraTS2021_00495_t2.nii.gz: (240, 240, 155)
